name: OCI

on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}-oci
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish to GitHub Container Registry
        env:
          REGISTRY: ghcr.io/appscode-charts
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          USERNAME: 1gtm
          APPSCODE_ENV: prod
        run: |
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}

      - name: Install Helm 3
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Publish OCI charts
        env:
          GITHUB_USER: 1gtm
          GITHUB_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          CHART_REPOSITORY: github.com/appscode/charts
        run: |
          REGISTRY_0=oci://ghcr.io/appscode-charts \
          ./hack/scripts/publish-oci-stable.sh
